import 'package:flutter/material.dart';

class LoadingView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final args = ModalRoute.of(context)?.settings.arguments as Map?;
    final Function onComplete = args?['onComplete'] ?? (_) {};

    // 이곳에서 실제 피드백 요청을 수행하고 완료되면 onComplete(feedback)를 호출합니다.
    Future.delayed(Duration(seconds: 3), () {
      final feedback = "This is a sample feedback generated by GPT.";
      onComplete(feedback);
    });

    return Scaffold(
      appBar: AppBar(
        title: Text("Loading"),
      ),
      body: Center(
        child: CircularProgressIndicator(),
      ),
    );
  }
}
