import 'package:flutter/material.dart';

class LoadingView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // 이곳에서 실제 피드백 요청을 수행하고 완료되면 피드백 화면으로 이동합니다.
    Future.delayed(Duration(seconds: 1), () {
      final feedback = "This is a sample feedback generated by GPT.";
      Navigator.of(context).pushNamed('/feedback', arguments: feedback);
    });

    return Scaffold(
      appBar: AppBar(
        title: Text("Loading"),
      ),
      body: Center(
        child: CircularProgressIndicator(),
      ),
    );
  }
}
