name: try_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: any
  flutter_dotenv: any
  dynamic_color: ^1.7.0
  intl: ^0.19.0
  google_fonts: ^6.2.1
  fluid_bottom_nav_bar: ^1.4.0
  diff_match_patch: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/images/
  fonts:
    - family: Ridibatang
      fonts:
        - asset: assets/fonts/RIDIBatang.otf
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Bold.otf
        - asset: assets/fonts/Merriweather-Black.otf